[exit_codes]
success = 0
generic_error = 1
policy_violation = 10
ownership_error = 20
lock_timeout = 30
atomic_swap_failed = 40
exdev_fallback_failed = 50
backup_missing = 60
restore_failed = 70
smoke_test_failed = 80
