[book]
authors = ["Switchyard Team"]
language = "en"
multilingual = false
src = "src"
title = "Switchyard: Operator and Integrator Guide"

[output.html]
no-section-label = true

# Optional preprocessors can be added later (e.g., linkcheck, mermaid)

[output.linkcheck]
follow-web-links = false
traverse-parent-directories = false
exclude = [
  # Linkcheck configuration examples; add patterns here if needed
]
