name: BDD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bdd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run BDD (failure-only output on failure)
        run: |
          python3 scripts/bdd_filter_results.py --fail-only
      - name: Upload BDD lastrun log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bdd-lastrun
          path: target/bdd-lastrun.log
          if-no-files-found: ignore
