name: Switchyard CI Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run CI test runner (switchyard crate)
        run: |
          python3 test_ci_runner.py -p switchyard-fs --nocapture
