name: MSRV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust (1.75)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.75.0
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build (MSRV)
        run: cargo build --all-features
