name: MSRV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  msrv:
    name: Build on MSRV toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust (1.85.0)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build workspace (all features)
        run: cargo build --all-features --workspace
