name: SPEC Traceability

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  traceability:
    name: SPEC traceability (non-blocking)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip install pyyaml
      - name: Run traceability tool
        working-directory: SPEC
        run: |
          python3 tools/traceability.py || true
      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spec-traceability-report
          path: SPEC/traceability.md
          if-no-files-found: warn
